steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', ''gcr.io/$PROJECT_ID/hoge-image', '.' ]
images: ['gcr.io/$PROJECT_ID/hoge-image']

# imagesフィールドを使用することでビルドが完了した後、Container Registry にイメージを格納できる
# https://cloud.google.com/build/docs/building/build-containers?hl=ja#store-images

# cloud buildでbuild構成ファイル（cloudbuild.yml）を使用してイメージのビルドとイメージのcontainer registryへの保存
# https://cloud.google.com/build/docs/building/build-containers?hl=ja